services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dailyworkerroster
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_DSN: "user:password@tcp(db:3306)/dailyworkerroster?parseTime=true"
      PORT: "8080"
    ports:
      - "8080:8080"
    command: ["./app"]

volumes:
  db_data: